name: 🐧 Linux (Flatpak)

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  flatpak:
    name: 📦 Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.96.1
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          rustc --version

      - name: Vendor Cargo dependencies
        run: cargo vendor

      - name: Build Flatpak
        run: |
          flatpak-builder --repo=repo build-dir flatpak/com.github.samfic.szyszka.yml --force-clean
