name: 🏁 Windows
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6

      - name: Install GTK dependencies and Rust (MSYS2)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-pkgconf

      - name: Build Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "VERS=release" >> $GITHUB_ENV
          cargo build --release
          cp target/release/szyszka.exe windows_szyszka.exe

      - name: Build Debug
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          sed -i 's/^\[profile\.dev\.package/#[profile.dev.package/; s/^opt-level = 3 # OPT PACKAGES/#opt-level = 3 # OPT PACKAGES/' Cargo.toml
          echo "VERS=debug" >> $GITHUB_ENV
          cargo build --profile fastci
          cp target/fastci/szyszka.exe windows_szyszka.exe

      - name: Store
        uses: actions/upload-artifact@v6
        with:
          name: szyszka-${{ runner.os }}-${{ env.VERS }}
          path: windows_szyszka.exe
